export const titleBannerData = [
  {
    id: 1,
    page: "ramonage",
    image: "/assets/pagesPrestations/titleBanner/title-banner-1.png",
    title: "Ramonage",
    text: "Parce que l’entretien annuel de chaudière est une obligation  légale, nous mettons tout en œuvre pour que cette opération  indispensable soit réalisée par nos techniciens qualifiés et compétents.",
  },
  {
    id: 2,
    page: "vmc",
    image: "/assets/pagesPrestations/titleBanner/title-banner-2.png",
    title: "Nettoyage et entretien VMC professionel",
    text: "En France, l’entretien des VMC est guidé par  l’arrêté du 31 janvier 1986, nécessitant des contrôles réguliers pour  assurer la qualité de l’air dans les établissements. BLM propose des  services pour maintenir la conformité et prolonger la durée de vie de  ces systèmes, incluant la délivrance d’un certificat électronique.",
  },
  {
    id: 3,
    page: "nettoyage-hottes-de-cuisine",
    image: "/assets/pagesPrestations/titleBanner/title-banner-3.png",
    title: "Hottes de cuisine",
    text: "BLM propose des activités de nettoyage pour lesquelles nos techniciens ont été formés",
  },
];
